version: "3"

services:
  data_base_service:
    image: mongo
    #image: iownit/aws-test:data_base_service
    build:
      context: ./database_service
      dockerfile: Dockerfile
    environment:
      #- ECS_ENGINE_AUTH_TYPE=docker
      #- ECS_ENGINE_AUTH_DATA={"https://registry-1.docker.io/v2/":{"username":"readonlyioi","password":"($$7sfr<&wz'N","email":"read_only@iownit.us"}}
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=get65478hk65241
      - MONGODB_APP_DB=albums
      - MONGODB_APP_USER=ualb4513
      - MONGODB_APP_PASS=f864cfd548hnbfet421
    logging:
      driver: awslogs
      options:
        awslogs-group: databaselogs
        awslogs-region: us-west-2
        awslogs-stream-prefix: wordpress
